### DISCUSSION TITLE
importing the data to home assistant

### DISCUSSION THREAD

**Discussion by CSH12** [beep-projects/SystaPi#17] [Ideas]
Hi beep, 

Not sure if you are familiar with home assistant, but I have googled a little and found the REST API integration for Home Assistant so that it might be possible to get the data also read in there...
Then, also the data can get stored to influxDB and visualized with Grafana. 

But actually I have no idea how to do that. 
Do you have any? 

Best regards 
Chris

**Comment by Villa-Buenavista** [comment]
Hi,

I follow this project because I sepcifically hope it might turn into a home assistant integration. I would ove to follow my heatin g and possibly set variables from Home Assistant. Unfortunately I lack coding skills and the installation still seems quite technical...

If there is an API I believe integration to HA is not a major issue. 

have a great Christmas everyone.

Gunnar

**Comment by beep-projects** [comment]
Hey, I only did some experiments with Home Assistant, that's why I implemented https://github.com/beep-projects/SystaPi#waterheater, but in the end I never found the time to implement my own sensor.

Reading guides like
https://michilehr.de/how-to-integrate-an-external-api-into-home-assistant-an-example-with-the-ambee-pollen-api
it doesn't sound very complex to write a sensor that displays values read from the status endpoint https://github.com/beep-projects/SystaPi#status

From the guide and without knowing the syntax, I would start with something like
```
### SystaPi

# Must be added in sensor.yml

- platform: rest
  scan_interval: 60
  resource: http://systapi:1337/SystaREST/status
  name: "SystaPi"
  headers:
    content-type: "application/json"
  json_attributes_path: "$.data"
  json_attributes:
    - outsideTemp
    - operationMode
    - hotWaterTemp

- platform: template
  sensors:
    systapi_outsidetemp:
      icon_template: "mdi:home-thermometer"
      friendly_name: "outside"
      value_template: >-
        {% set state = state_attr('sensor.systapi', 'outsideTemp') %}
- platform: template
  sensors:
    systapi_operation_mode:
      icon_template: "mdi:form-dropdown"
      friendly_name: "mode"
      value_template: >-
        {% set state = state_attr('sensor.systapi', 'operationMode') %}
- platform: template
  sensors:
    systapi_hotwater_temp:
      icon_template: "mdi:water-thermometer"
      friendly_name: "hotwater"
      value_template: >-
        {% set state = state_attr('sensor.systapi', 'hotWaterTemp') %}
```

I hope that helps,
Beep
